version: "3.9"
services:
  reap-one-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "ghcr.io/reaudioplayer/reap-one:dev"
    ports:
      - "1234:80"
    volumes:
      - ./src/:/opt/reAudioPlayer/
      - ./src/cache/:/opt/reAudioPlayer/server/_cache/
    stop_signal: SIGTERM
