name: mypy

on:
  push:
    paths:
      - 'src/server/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./src/server
      run: |
        python3 -m pip install --upgrade pip
        pip3 install mypy types-requests
        pip3 install -r requirements.txt
    - name: Analysing...
      id: main
      working-directory: ./src/server
      run: |
        mypy
      continue-on-error: false